baseURL = "https://bitterfq.github.io/"
languageCode = "en-us"
title = "BitterFq's Corner 🍻"
theme = "typo"

[params]
  author = "bitterfq"
  description = "bitterfq's blog"
  github = "https://github.com/bitterfq"
  showLastUpdated = true
  
  homeIntroTitle = "Hey, I'm Aman!"
  homeIntroContent = """
  I'm a **data engineer & data scientist**, currently pursuing my **Master’s at USF**,  
  where I focus on **scalable data systems, distributed computing, and geospatial analytics**.  

  I work at the intersection of **big data, machine learning, and automation**,  
  building systems that transform **raw data into real-world insights**.  

  Right now, I’m developing **high-throughput data pipelines, working with geospatial ML,  and pushing the limits of efficiency in large-scale data processing.**  

  """



# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/bitterfq/"


[[params.social]]
name = "github"
url = "https://github.com/bitterfq"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "resume"
url = "/resume.pdf"
weight = 3
  
[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"

  