baseURL = "https://bitterfq.github.io/"
languageCode = "en-us"
title = "My Tech Blog"
theme = "typo"

[params]
  author = "bitterfq"
  description = "A simple retro-style tech blog."
  github = "https://github.com/bitterfq"
  showLastUpdated = true
